n<- as.integer(readline(prompt = "enter the number of students"))
usn<-vector(mode = "character",length = n)
name<-vector(mode = "character",length = n)
marks<-vector(mode = "numeric",length = n)
print("enter USN")
for(i in 1:n)
    usn[i]<-as.character(readline())
print("enter name")
for(i in 1:n)
  name[i]<-as.character(readline())
print("enter marks")
for(i in 1:n)
  marks[i]<-as.integer(readline())
student<-data.frame(usn,name,marks)
print("student details are follows")
print(student)


print("enter age")
age<-vector(mode = "integer", length = n)
for(i in 1:n)
  age[i]<-as.integer(readline())
student<-cbind(student,age)
print(student)
for(i in 1:n)
  if(student[i, ][3] > 25)
    if(student[i, ][4] > 20)
      print(student[i, ])
