n<-as.integer(readline(prompt = "enter the number of employees"))
empid<-vector(mode = "character",length = n)
empname<-vector(mode = "character",length = n)
doj<-vector(mode = "character",length = n)
empcode<-vector(mode = "character",length = n)
desig<-vector(mode = "character",length = n)
dept<-vector(mode = "character",length = n)
print("enter the details")
for(i in 1:n)
  empid[i]<-as.character(readline())
  empname[i]<-as.character(readline())
  doj[i]<-as.character(readline())
  empcode[i]<-as.character(readline())
  dept[i]<-as.character(readline())
  desig[i]<-as.character(readline())
emp<-data.frame(empid,empname,doj,empcode,dept,desig)
print(emp)
write.csv(emp,"emp.csv")
reademp<-read.csv("emp.csv")
print("enter a new row")
u<-readline(prompt = "empid")
n<-readline(prompt = "empname")
m<-readline(prompt = "doj")
a<-readline(prompt = "empcode")
s<-readline(prompt = "dept")
t<-readline(prompt = "desig")
x<-data.frame(u,n,m,a,s,t)
write.table(x,"emp.csv",col.names = F,append = T,row.names = T,quote = F,sep = ",")